# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Calculadora vb.App

on:
  push:
    tags:
      - 'v1.0.0'   # Solo se ejecuta cuando subas el tag v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: App-VB
        path: ./publish/**

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.0
        name: "Versión 1.0.0"
        body: "Primera versión estable de la aplicación 🚀"
        files: ./publish/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
